### ISSUE TITLE
sharing data sets between instances

### ISSUE THREAD

**Issue by raedah** [raedahgroup/dcrextdata#159]
Devise a way to share data sets between dcrextdata instances. 
Data sharing would take place over an API and the whole data set can be duplicated locally to be queried from the db. Would create unique names and dbnames per instance. conf file would support settings for configuring other instances to sync data from. data sync would be incremental.

**Comment by xaur** [comment]
Ideally the same tool can be used by researches to (incrementally) grab the data sets for local study.
